# Generated by Django 2.2 on 2019-04-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_start', models.BooleanField(default=True)),
                ('game_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('ship1', models.CharField(blank=True, max_length=15, null=True)),
                ('ship2', models.CharField(blank=True, max_length=12, null=True)),
                ('ship3', models.CharField(blank=True, max_length=9, null=True)),
                ('ship4', models.CharField(blank=True, max_length=6, null=True)),
                ('shooted', models.CharField(blank=True, max_length=250, null=True)),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='playground.Player')),
            ],
        ),
    ]
