# Generated by Django 2.2 on 2019-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game_start',
            field=models.BooleanField(default=False),
        ),
    ]
