# Generated by Django 2.2 on 2019-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_room_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warzone',
            name='shooted',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
