# Generated by Django 2.2 on 2019-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_auto_20190416_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warzone',
            name='ship1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warzone',
            name='ship2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warzone',
            name='ship3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warzone',
            name='ship4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warzone',
            name='shooted',
            field=models.CharField(default='', max_length=250),
        ),
    ]
